/*
 * Project X
 *
 * OpenAPI definition for project X endpoint and resources
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"flag"
	"log"
	"net/http"

	openapi "github.com/GIT_USER_ID/GIT_REPO_ID/go"
	"github.com/GIT_USER_ID/GIT_REPO_ID/go/testdb"
	"github.com/kelseyhightower/envconfig"
)

type AppConfig struct {
	PostgresDSN string `envconfig:"POSTGRES_DSN" default:"host=localhost dbname=project port=5432 sslmode=disable"`
}

var Config AppConfig

func init() {
	flag.Parse()
	_ = envconfig.Process("", &Config)
}

func main() {
	log.Printf("Server started")

	db, err := testdb.New(Config.PostgresDSN)
	if err != nil {
		panic(err)
	}

	_ = db
	ApiApiService := openapi.NewApiApiService()
	ApiApiController := openapi.NewApiApiController(ApiApiService)

	DefaultApiService := openapi.NewDefaultApiService()
	DefaultApiController := openapi.NewDefaultApiController(DefaultApiService)

	TestsApiService := openapi.NewTestsApiService()
	TestsApiController := openapi.NewTestsApiController(TestsApiService)

	router := openapi.NewRouter(ApiApiController, DefaultApiController, TestsApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
