/*
 * TraceTest
 *
 * OpenAPI definition for TraceTest endpoint and resources
 *
 * API version: 0.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type HttpRequestHeaders struct {
	Key string `json:"key,omitempty"`

	Value string `json:"value,omitempty"`
}

// AssertHttpRequestHeadersRequired checks if the required fields are not zero-ed
func AssertHttpRequestHeadersRequired(obj HttpRequestHeaders) error {
	return nil
}

// AssertRecurseHttpRequestHeadersRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of HttpRequestHeaders (e.g. [][]HttpRequestHeaders), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseHttpRequestHeadersRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aHttpRequestHeaders, ok := obj.(HttpRequestHeaders)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertHttpRequestHeadersRequired(aHttpRequestHeaders)
	})
}
